name: GoTroll
main: gotroll\Loader
version: 1.0.0
api: 1.10.0
load: POSTWORLD
author: Gamecrafter
description: Troll players in the server and make them mad!
website: https://github.com/Gamecrafter/Small-Plugins/tree/master/GoTroll
commands:
 gotroll:
  description: Shows all the sub-commands for /gotroll
  usage: /gotroll <sub-command> [parameter]
  permission: gotroll.command.troll
  aliases: [gt]
