name: PlanB
main: planb\PlanBLoader
version: 1.0.0
api: 1.10.0
load: POSTWORLD
author: Gamecrafter
description: Hackers can't cripple your server anymore!
website: https://github.com/Gamecrafter/Small-Plugins/tree/master/PlanB
commands:
 planb:
  description: Shows all the sub-commands for /planb
  usage: /planb <sub-command>
  permission: planb.command.planb
  aliases: [pb]
permissions:
 planb:
  default: false
  children:
   planb.command:
    default: false
    children:
     planb.command.help:
      default: true
     planb.command.restore:
      default: notop
