name: LocatorPro
main: locatorpro\Loader
version: 1.0.0
api: 1.10.0
load: POSTWORLD
author: Gamecrafter
description: Everything is about the coordinates!
website: https://github.com/Gamecrafter/Small-Plugins/tree/master/LocatorPro
commands:
 getpos:
  description: Gets a player's current coordinates, level name, and which direction they are facing
  usage: /getpos <player>
  permission: locator.command.getpos
permissions:
 locatorpro:
  default: op
  children:
   locatorpro.action:
    default: op
   locatorpro.command:
    default: op
    children:
     locatorpro.command.getpos:
      default: true
      children:
       locatorpro.command.getpos.others:
        default: true
       locatorpro.command.getpos.self:
        default: true
