name: iManager
main: iManager\Loader
version: 1.1.0
api: 1.10.0
load: STARTUP
author: Gamecrafter
description: Manage your server like never before!
website: https://github.com/Gamecrafter/Small-Plugins/tree/master/iManager
commands:
 server:
  description:
  usage: /server <addresslist/gamemodelist/healthlist/kickall/killall/moneylist/opall/oplist>
  permission: imanager.command.check
permissions:
 imanager:
  default: op
  children:
   imanager.command:
    default: op
    children:
     imanager.command.server:
      default: op
