name: iManager
main: iManager\Loader
version: 1.1.0
api: 1.0.0
load: STARTUP
author: Gamecrafter
description: Manage your server like never before!
website: https://github.com/Gamecrafter/Small-Plugins/tree/master/iManager
commands:
 check:
  description:
  usage: /check <address/gamemode/health/money/op/money>
  permission: imanager.command.check
permissions:
 imanager:
  default: op
  description: Allows access to all iManager features
  children:
   imanager.command:
    default: op
    description: Allows use of all iManager commands
    children:
     imanager.command.check:
      default: op
      description: Allows use of /check
