name: iManager
main: imanager\iManagerAPI
version: 1.3.0
api: 1.10.0
load: STARTUP
author: Gamecrafter
description: Manage your server like never before!
website: https://github.com/Gamecrafter/PocketMine-Plugins/tree/master/iManager
commands:
 imanager:
  description: Shows all the sub-commands for /imanager
  usage: /imanager <sub-command> [parameters]
  permission: imanager.command.imanager
  aliases: [im]
permissions:
 imanager:
  default: op
  children:
   imanager.command:
    default: op
    children:
     imanager.command.imanager:
      default: op
