name: GlobalShield
main: GlobalShield\Loader
version: 1.1.0
api: 1.10.0
load: STARTUP
author: Gamecrafter
description: Shield all of your worlds from griefers!
website: https://github.com/Gamecrafter/Small-Plugins/tree/master/GlobalShield
permissions:
 globalshield:
  default: op
  children:
   globalshield.action:
    default: op
    children:
     globalshield.action.break:
      default: op
     globalshield.action.empty:
      default: op
     globalshield.action.fill:
      default: op
     globalshield.action.interact:
      default: op
     globalshield.action.place:
      default: op
