name: GlobalShield
main: globalshield\Loader
version: 1.1.0
api: 1.10.0
load: POSTWORLD
author: Gamecrafter
description: Disable/enable certain things in certain levels!
website: https://github.com/Gamecrafter/Small-Plugins/tree/master/GlobalShield
permissions:
 globalshield:
  default: op
  children:
   globalshield.action:
    default: op
    children:
     globalshield.action.bypass:
      default: op
