#Configuration file for LocatorPro v1.0.0
enable:
 teleport: true
 #Set to true to teleport players back to set position after player has a y-coordinate above maximum-y or below minimum-y
limit:
 maximum-y:
 #Highest y-coordinate before player is teleported back to set position
 minimum-y:
 #Lowest y-coordinate before player is teleported back to set position
spawn-point:
 x:
 #Sets the spawn x
 y:
 #Sets the spawn y
 z:
 #Sets the spawn z
 yaw:
 #Sets the spawn yaw
 pitch:
 #Sets the spawn pitch
 level:
 #Sets the spawn level
version: 1.0.0
#Do not change the version, it is used for internal purposes
