#Configuration file for Commander v1.0.0
enable:
 command:
 #Set to true for each event you want commands to be run on
  on-block-break: true
  on-block-place: true
  on-player-bed-enter: true
  on-player-bed-leave: true
  on-player-bucket-empty: true
  on-player-bucket-fill: true
  on-player-death: true
  on-player-drop-item: true
  on-player-gamemode-change: true
  on-player-interact: true
  on-player-item-consume: true
  on-player-item-held: true
  on-player-join: true
  on-player-kick: true
  on-player-quit: true
  on-player-respawn: true
run:
 on-block-break: 
  - kick {player}
 on-block-place: 
  - tell {player} Please stop placing blocks!
 on-player-bed-enter: 
  - tell {player} Good night, {player}...
 on-player-bed-leave: 
  - tell {player} Good morning, sleepyhead!
 on-player-bucket-empty: 
  - kick {player}
 on-player-bucket-fill: 
  - kick {player}
 on-player-death: 
  - ban {player}
 on-player-drop-item: 
  - say {player} dropped something!
 on-player-gamemode-change: 
  - say {player} switched gamemodes!
 on-player-interact: 
  - tell {player} Stop being interactive!
 on-player-item-consume: 
  - say {player} is snacking!
 on-player-item-held: 
  - kick {player}
 on-player-join: 
  - tell {player} Welcome, {player}. Play on this server next time!
 on-player-kick: 
  - say {player} was kicked for being too awesome!
 on-player-quit: 
  - ban {player}
 on-player-respawn: 
  - say {player} has resurrected!
version: 1.0.0
#Do not change the version, it is used for internal purposes
