name: GearUp
main: gearup\Loader
version: 1.0.0
api: 1.10.0
load: POSTWORLD
author: Gamecrafter
description: Gear up yourself with ease!
website: https://github.com/Gamecrafter/PocketMine-Plugins/tree/master/GearUp
commands:
 gearup:
  description: 
  usage: /gear [parameters] [parameters]
  permission: gearup.command.gearup
