name: GearUp
main: GearUp\Loader
version: 1.0.0
api: 1.0.0
load: STARTUP
author: Gamecrafter
description: Gear up yourself with ease!
website: https://github.com/Gamecrafter/Small-Plugins/tree/master/GearUp
