name: EffectsPro
main: effectspro\EffectsProAPI
version: 1.0.0
api: 1.12.0
load: POSTWORLD
author: Gamecrafter
description: 
website: https://github.com/Gamecrafter/PocketMine-Plugins/tree/master/EffectsPro
