#Config file for LifeCare by Gamecrafter;
auto-heal:
#Set to true to enable auto-healing
maximum-health:
#Highest amount of health possible
mininum-health:
#Lowest amount of health possible before auto-heal starts, if enabled
