#Configuration file for LifeCare by Gamecrafter
auto-heal: false
#Set to true to enable auto-healing
default-health: 20
#Default amount of health for a player
maximum-health: 20
#Highest amount of health possible
mininum-health: 0
#Lowest amount of health possible before auto-heal starts, if enabled
