#Configuration file for LifeCare v1.0.0
auto-heal: false
#Set to true to enable auto-healing
default-health: 20
#Default amount of health for a player
maximum-health: 20
#Highest amount of health possible
mininum-health: 0
#Lowest amount of health possible before auto-heal starts, if enabled
version: 1.0.0
#Do not change the version, it is used for internal purposes