#Configuration file for BundleCommand v1.0.0
bundle:
 lockdown:
  default: true
  commands:
  - imanager kickall
  - stop
 party:
  default: op
  commands:
  - give {player} 264
  - newcurrency add {player} 1000
