#Configuration file for BundleCommand v1.0.0
enable:
 auto-update: true
bundle:
 lockdown:
  default: true
  commands:
  - imanager kickall
  - stop
 party:
  default: op
  commands:
  - give {player} 264
  - newcurrency give {player} 1000
message:
 error: "Sorry, that command bundle could not be found!"
