name: NoBoom
main: NoBoom\Loader
version: 1.0.0
api: [1.0.0]
load: STARTUP
author: Gamecrafter
description: Prevent any explosions from taking place in your server!
website: https://github.com/Gamecrafter/Example-Plugins/tree/master/NoBoom
