name: LifeCare
main: LifeCare\Loader
version: 1.0.0
api: 1.0.0
load: STARTUP
author: Gamecrafter
description: Manage all of the players' health!
website: https://github.com/Gamecrafter/Small-Plugins/tree/master/LifeCare
