name: SimpleChat
main: SimpleChat\Loader
version: 1.0.0
api: 1.0.0
load: STARTUP
author: Gamecrafter
description: Change the way the chat looks on your server!
website: https://github.com/Gamecrafter/Small-Plugins/tree/master/SimpleChat
