#Configuration file for MyTag v1.1.0
version: 1.1.0
#Do not change the version, it is used for internal purposes
enable:
 auto-set: true
 #Set to true to set the tag to the player's preferences on-join
op-prefix: "[Staff]"
#Name tag prefix for /mytag op, example: [Admin] Steve
preferred-economy: 
#Will be used for /mytag money, will be implemented in v1.2.0
