name: WarpArrow
main: WarpArrow\Loader
version: 1.0.0
api: 1.0.0
load: STARTUP
author: Gamecrafter
description: Teleport to where your arrow lands!
website: https://github.com/Gamecrafter/Small-Plugins/tree/master/WarpArrow
