name: SignsPro
main: SignsPro\Loader
version: 1.0.0
api: 1.10.0
load: STARTUP
author: Gamecrafter
description: Control and customize the signs in your server!
website: https://github.com/Gamecrafter/Small-Plugins/tree/master/SignsPro
permission:
 signspro:
  default: op
  description: Allows access to all SignsPro features
  children:
   signspro.action:
    default: op
    description: Allows access to all SignsPro actions
    children:
     signspro.action.create:
      default: true
      description: Allows creation of SignsPro signs
     signspro.action.use:
      default: true
      description: Allows usage of SignsPro signs
