name: SignsPro
main: signspro\Loader
version: 1.0.0
api: 1.10.0
load: STARTUP
author: Gamecrafter
description: Control and customize the signs in your server!
website: https://github.com/Gamecrafter/Small-Plugins/tree/master/SignsPro
permission:
 signspro:
  default: op
  children:
   signspro.action:
    default: op
    children:
     signspro.action.create:
      default: true
     signspro.action.use:
      default: true
