#Configuration file for MyChat v1.0.0
characters:
 A:
 B:
 C:
 D:
 E:
 F:
 G:
 H:
 I:
 J:
 K:
 L:
 M:
 N:
 O:
 P:
 Q:
 R:
 S:
 T:
 U:
 V:
 W:
 X:
 Y:
 Z:
 a:
 b:
 c:
 d:
 e:
 f:
 g:
 h:
 i:
 j:
 k:
 l:
 m:
 n:
 o:
 p:
 q:
 r:
 s:
 t:
 u:
 v:
 w:
 x:
 y:
 z:
 1:
 2:
 3:
 4:
 5:
 6:
 7:
 8:
 9:
format: "{player}: {message}"
#Set chat format layout, default is name: message
#{ip} shows player IP address
#{level} shows player level
#{message} shows message
#{player} shows player name
#{port} shows port number
mute:
 on-join-message:
 on-quit-message:
version: 1.0.0
#Do not change the version, it is used for internal purposes
