#Configuration file for MyChat v1.0.0
enable:
 mute:
  on-death-message: true
  #Set to false to mute on-death-message
  on-join-message: true
  #Set to false to mute on-join-message
  on-quit-message: true
  #Set to false to mute on-quit-message
format: "{player}: {message}"
#Sets chat format, refer to key.txt
version: 1.0.0
#Do not change the version, it is used for internal purposes
