name: EasyBeacon
main: easybeacon\Loader
version: 1.0.0
api: 1.10.0
load: POSTWORLD
author: Gamecrafter
description: Create beacons in your worlds!
website: https://github.com/Gamecrafter/Small-Plugins/tree/master/EasyBeacon
permission:
 easybeacon:
  default: op
  children:
   easybeacon.action:
    default: op
    children:
     easybeacon.action.create:
      default: true
