name: ServerPopups
main: serverpopups\ServerPopupsAPI
version: 1.0.0
api: 1.12.0
load: POSTWORLD
author: Gamecrafter
description: Send popups to the players!
website: https://github.com/Gamecrafter/Small-Plugins/tree/master/ServerPopups
commands:
 serverpopups:
  description:
  usage: /serverpopups <sub-command> [parameter]
  permission: serverpopups.command.serverpopups
  aliases: [sp]
