name: FistBlaster
main: fistblaster\FistBlasterLoader
version: 1.0.0
api: 1.10.0
load: POSTWORLD
author: Gamecrafter
description: Blow up everything when you touch a block!
website: https://github.com/Gamecrafter/PocketMine-Plugins/tree/master/FistBlaster
commands:
 fistblaster:
  description:
  usage: /fistblaster
  permission: fistblaster.command.fistblaster
  aliases: [fb]
permissions:
 fistblaster:
  default: op
  children:
   fistblaster.command:
    default: op
    children:
     fistblaster.command.blast:
      default: op
