name: IPTag
main: IPTag\Loader
version: 1.0.0
api: 1.0.0
load: STARTUP
author: Gamecrafter
description: Show the player's address above their head!
website: https://github.com/Gamecrafter/Small-Plugins/tree/master/IPTag
