name: IPTag
main: IPTag\Main
version: 1.0.0
api: [1.0.0]
load: STARTUP
author: Gamecrafter
description: Show the player's address above their head!
website: https://github.com/Gamecrafter/Example-Plugins/tree/master/IPTag
