name: MyTag
main: mytag\Loader
version: 1.1.0
api: 1.10.0
load: STARTUP
author: Gamecrafter
description: Players get to control what is on their name tag!
website: https://github.com/Gamecrafter/Small-Plugins/tree/master/MyTag
commands:
 tag:
  description: 
  usage: /tag <address/chat/health/help/hide/money/op/pos/restore/view>
  permission: mytag.command.tag
permissions:
 mytag:
  default: op
  children:
   mytag.command:
    default: op
    children:
     mytag.command.tag:
      default: true
