name: MyTag
main: mytag\Loader
version: 1.1.0
api: 1.10.0
load: POSTWORLD
author: Gamecrafter
description: Players get to control what is on their name tag!
website: https://github.com/Gamecrafter/Small-Plugins/tree/master/MyTag
commands:
 mytag:
  description: 
  usage: /mytag <address/chat/health/help/hide/money/op/restore/view>
  permission: mytag.command.tag
  aliases: [mt]
permissions:
 mytag:
  default: op
  children:
   mytag.command:
    default: op
    children:
     mytag.command.mytag:
      default: true
