name: MyTag
main: mytag\MyTagAPI
version: 1.2.0
api: 1.10.0
load: POSTWORLD
author: Gamecrafter
description: Players get to control what is on their name tag!
website: https://github.com/Gamecrafter/PocketMine-Plugins/tree/master/MyTag
commands:
 mytag:
  description: Shows all the sub-commands for /mytag
  usage: /mytag <sub-command> [parameters]
  permission: mytag.command.mytag
  aliases: [mt]
permissions:
 mytag:
  default: op
  children:
   mytag.command:
    default: op
    children:
     mytag.command.mytag:
      default: true
