name: ServerLaw
main: serverlaw\Loader
version: 1.0.0
api: 1.10.0
load: STARTUP
author: Gamecrafter
description: Let there be law and order in your server!
website: https://github.com/Gamecrafter/Small-Plugins/tree/master/ServerLaw
commands:
 laws:
  description: Get a list of laws for the server
  permission: serverlaw.command.laws
  aliases: [sl]
