name: AdvancedText
main: advancedtext\AdvancedTextAPI
version: 1.0.0
api: 1.12.0
load: POSTWORLD
author: Gamecrafter
description: 
website: https://github.com/Gamecrafter/PocketMine-Plugins/tree/master/AdvancedText
commands:
 advancedtext:
  description: Shows all the sub-commands for /advancedtext
  usage: /advancedtext <sub-command> [parameters]
  permission: advancedtext.command.advancedtext
  aliases: [at]
