name: DoMath
main: domath\Loader
version: 1.0.0
api: 1.10.0
load: STARTUP
author: Gamecrafter
description: It's easy to do math now!
website: https://github.com/Gamecrafter/PocketMine-Plugins/tree/master/DoMath
commands:
 domath:
  description:
  usage: /domath <sub-command> [parameters]
  permission: domath.command.domath
  aliases: [dm]
permissions:
 domath:
  default: op
  children:
   domath.command:
    default: op 
    children:
     domath.command.domath:
      default: true
