name: Commander
main: Commander\Loader
version: 1.0.0
api: 1.10.0
load: STARTUP
author: Gamecrafter
description: Execute commands with convenience!
website: https://github.com/Gamecrafter/Small-Plugins/tree/master/Commander
