name: KickOnJoin
main: KickOnJoin\Loader
version: 1.0.0
api: [1.0.0]
load: STARTUP
author: Gamecrafter
description: Kick players when they join!
website: https://github.com/Gamecrafter/Example-Plugins/tree/master/KickOnJoin
