#Configuration file for GlobalShield v1.1.0
version: 1.1.0
#Do not change the version, it is used for internal purposes
level:
 world:
  block-breaking:
  block-placing:
  bucket-emptying:
  bucket-filling:
  explosions:
  pvp:
