name: Rewinder
main: Rewinder\Main
version: 1.0.0
api: [1.0.0]
load: STARTUP
author: Gamecrafter
description: Go back to the place of your last death!
website: https://github.com/Gamecrafter/Example-Plugins/tree/master/Rewinder
